FROM node:22-alpine
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate
COPY package.json pnpm-lock.yaml ./
RUN pnpm install
COPY . .
EXPOSE 3003
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3003
CMD ["pnpm", "run", "dev"]
